version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres01
    networks:
      - common_network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: worker
      POSTGRES_DB: superblog
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    networks:
      - common_network
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: secret
    
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - common_network
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodbdata:/data/db

  redis:
    image: redis
    container_name: redis
    networks:
      - common_network
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  mongodbdata:
  redisdata:

networks:
  common_network:
    driver: bridge
